In [1]:
%load_ext zipline

In [2]:
%%zipline --start 2018-4-10 --end 2018-4-25

from zipline.api import *  #symbol, order #, #last_trade  #get_current_holdings, get_current_allocations
from zipline.pipeline import Pipeline

from zipline.pipeline.builtin import BlackNames

STOCKS = ['000333', '600771', '600000', '000033', '000157']


def make_pipeline():
    return Pipeline(
        columns={},
        screen= ~BlackNames(STOCKS),
    )


def initialize(context):
    attach_pipeline(make_pipeline(), 'pipeline_data')


def handle_data(context, data):
    context.output = pipeline_output('pipeline_data')
    for s in context.output.index:
        order(s, 1000)
    print(context.get_current_allocations())

Series([], dtype: float64)
中联重科(000157)    0.000420
美的集团(000333)    0.005298
浦发银行(600000)    0.001191
广誉远(600771)     0.005050
dtype: float64
中联重科(000157)    0.000834
美的集团(000333)    0.010374
浦发银行(600000)    0.002356
广誉远(600771)     0.010384
dtype: float64
中联重科(000157)    0.001252
美的集团(000333)    0.015406
浦发银行(600000)    0.003509
广誉远(600771)     0.014835
dtype: float64
中联重科(000157)    0.001670
美的集团(000333)    0.019937
浦发银行(600000)    0.004625
广誉远(600771)     0.019921
dtype: float64
中联重科(000157)    0.002078
美的集团(000333)    0.024986
浦发银行(600000)    0.005784
广誉远(600771)     0.024135
dtype: float64
中联重科(000157)    0.002500
美的集团(000333)    0.029284
浦发银行(600000)    0.007049
广誉远(600771)     0.029627
dtype: float64
中联重科(000157)    0.002919
美的集团(000333)    0.036094
浦发银行(600000)    0.008259
广誉远(600771)     0.034463
dtype: float64
中联重科(000157)    0.003311
美的集团(000333)    0.041102
浦发银行(600000)    0.009284
广誉远(600771)     0.040038
dtype: float64
中联重科(000157)    0.003729
美的集团(000333)    0.046886
浦发银行(600000)    0.010449
广誉远(600771)     0.043058
dtype: float64
中联重科(000157)    0.004167
美的集团(000333)    0.053377
浦发银行(600000)    0.011742
广誉远(600771)     0.050487
dtype: float64
中联重科(000157)    0.004584
美的集团(000333)    0.057710
浦发银行(600000)    0.012788
广誉远(600771)     0.056437
dtype: float64
[2018-06-17 14:11:01.974745] INFO: zipline.finance.metrics.tracker: 模拟12个交易日
首个开盘时间: 2018-04-10 01:31:00+00:00
最后收盘时间: 2018-04-25 07:00:00+00:00

,algo_volatility,algorithm_period_return,alpha,benchmark_period_return,benchmark_volatility,beta,capital_used,ending_cash,ending_exposure,ending_value,...,short_exposure,short_value,shorts_count,sortino,starting_cash,starting_exposure,starting_value,trading_days,transactions,treasury_period_return
2018-04-10 07:00:00+00:00,NaN,0.000000,NaN,0.019269,NaN,NaN,0.000,1.000000e+07,0.0,0.0,...,0.0,0.0,0,NaN,1.000000e+07,0.0,0.0,1,[],0.0
2018-04-11 07:00:00+00:00,0.000072,-0.000006,-0.001886,0.022168,0.184370,0.000388,-119653.795,9.880346e+06,119590.0,119590.0,...,0.0,0.0,0,-11.224972,1.000000e+07,0.0,0.0,2,"[{'amount': 1000, 'dt': 2018-04-11 07:00:00+00...",0.0
2018-04-12 07:00:00+00:00,0.000119,0.000002,0.000454,0.011862,0.233517,-0.000263,-119803.870,9.760542e+06,239480.0,239480.0,...,0.0,0.0,0,3.208852,9.880346e+06,119590.0,119590.0,3,"[{'amount': 1000, 'dt': 2018-04-12 07:00:00+00...",0.0
2018-04-13 07:00:00+00:00,0.005041,-0.000632,-0.042898,0.004728,0.209909,0.009825,-116662.300,9.643880e+06,349800.0,349800.0,...,0.0,0.0,0,-7.908901,9.760542e+06,239480.0,239480.0,4,"[{'amount': 1000, 'dt': 2018-04-13 07:00:00+00...",0.0
2018-04-16 07:00:00+00:00,0.004714,-0.001040,-0.046123,-0.011437,0.219522,0.011278,-115321.630,9.528558e+06,461040.0,461040.0,...,0.0,0.0,0,-9.791071,9.643880e+06,349800.0,349800.0,5,"[{'amount': 1000, 'dt': 2018-04-16 07:00:00+00...",0.0
2018-04-17 07:00:00+00:00,0.004918,-0.001638,-0.052785,-0.027068,0.215193,0.014203,-113840.890,9.414718e+06,568900.0,568900.0,...,0.0,0.0,0,-11.029829,9.528558e+06,461040.0,461040.0,6,"[{'amount': 1000, 'dt': 2018-04-17 07:00:00+00...",0.0
2018-04-18 07:00:00+00:00,0.004924,-0.001574,-0.044032,-0.022489,0.204040,0.015846,-113980.960,9.300737e+06,683520.0,683520.0,...,0.0,0.0,0,-9.812867,9.414718e+06,568900.0,568900.0,7,"[{'amount': 1000, 'dt': 2018-04-18 07:00:00+00...",0.0
2018-04-19 07:00:00+00:00,0.011791,0.000135,0.015416,-0.010664,0.207437,0.034799,-116842.390,9.183894e+06,817460.0,817460.0,...,0.0,0.0,0,0.800345,9.300737e+06,683520.0,683520.0,8,"[{'amount': 1000, 'dt': 2018-04-19 07:00:00+00...",0.0
2018-04-20 07:00:00+00:00,0.011132,0.000437,0.031413,-0.023897,0.204349,0.029066,-117282.610,9.066612e+06,937760.0,937760.0,...,0.0,0.0,0,2.412185,9.183894e+06,817460.0,817460.0,9,"[{'amount': 1000, 'dt': 2018-04-20 07:00:00+00...",0.0
2018-04-23 07:00:00+00:00,0.012516,-0.000873,-0.008035,-0.022477,0.193740,0.025036,-115651.795,8.950960e+06,1040310.0,1040310.0,...,0.0,0.0,0,-2.688357,9.066612e+06,937760.0,937760.0,10,"[{'amount': 1000, 'dt': 2018-04-23 07:00:00+00...",0.0
2018-04-24 07:00:00+00:00,0.023336,0.003234,0.076575,-0.002450,0.213490,0.066429,-120224.080,8.830736e+06,1201600.0,1201600.0,...,0.0,0.0,0,9.538480,8.950960e+06,1040310.0,1040310.0,11,"[{'amount': 1000, 'dt': 2018-04-24 07:00:00+00...",0.0
2018-04-25 07:00:00+00:00,0.022387,0.002987,0.070465,-0.006287,0.204262,0.066977,-119983.960,8.710752e+06,1319120.0,1319120.0,...,0.0,0.0,0,8.345344,8.830736e+06,1201600.0,1201600.0,12,"[{'amount': 1000, 'dt': 2018-04-25 07:00:00+00...",0.0